{{- $fullname := .Values.fullnameOverride | default .Release.Name }}
{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: oracle
    app.kubernetes.io/instance: {{ $fullname }}
type: Opaque
stringData:
  ORACLE_PASSWORD: {{ .Values.auth.password | quote }}
{{- end }}
